# -*- coding: utf-8 -*-
"""ride sharing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PvkrONaP_9vOqn6n0116ybgAQgZFbP6n

**Ride Data Analysis - explore and analyze ride sharing dataset**
"""

# ============================================================
# RIDE-SHARING DATA ANALYSIS PROJECT FOR GOOGLE COLAB
# ============================================================

# Install required libraries (run this first in Colab)
import subprocess
import sys

def install_packages():
    packages = ['pandas', 'numpy', 'matplotlib', 'seaborn', 'scikit-learn', 'scipy']
    for package in packages:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", package])

print("Installing required packages...")
install_packages()
print("Installation complete!\n")

# ============================================================
# IMPORT LIBRARIES
# ============================================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

# Set style for better visualizations
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (14, 6)

# ============================================================
# CREATE SAMPLE RIDE-SHARING DATASET
# ============================================================
print("=" * 60)
print("CREATING SAMPLE RIDE-SHARING DATASET")
print("=" * 60)

np.random.seed(42)

# Generate synthetic ride data
n_rides = 5000

data = {
    'ride_id': np.arange(1, n_rides + 1),
    'pickup_time': [datetime.now() - timedelta(days=np.random.randint(0, 365)) for _ in range(n_rides)],
    'ride_duration_minutes': np.random.gamma(shape=2, scale=15, size=n_rides),
    'distance_km': np.random.gamma(shape=2, scale=5, size=n_rides),
    'base_fare': np.random.uniform(2, 5, n_rides),
    'distance_fare': np.random.uniform(1, 3, n_rides),
    'surge_multiplier': np.random.choice([1.0, 1.5, 2.0, 2.5], n_rides, p=[0.7, 0.15, 0.1, 0.05]),
    'passenger_rating': np.random.uniform(1, 5, n_rides),
    'driver_rating': np.random.uniform(1, 5, n_rides),
    'vehicle_type': np.random.choice(['Economy', 'Comfort', 'Premium'], n_rides, p=[0.6, 0.3, 0.1]),
    'payment_method': np.random.choice(['Card', 'Cash', 'Wallet'], n_rides, p=[0.7, 0.15, 0.15]),
    'is_cancelled': np.random.choice([0, 1], n_rides, p=[0.95, 0.05]),
}

df = pd.DataFrame(data)

# Calculate total fare
df['total_fare'] = (df['base_fare'] + df['distance_fare'] * df['distance_km']) * df['surge_multiplier']

# Add time features
df['hour'] = df['pickup_time'].dt.hour
df['day_of_week'] = df['pickup_time'].dt.day_name()
df['date'] = df['pickup_time'].dt.date

# Calculate ride rating (average of passenger and driver ratings)
df['ride_rating'] = (df['passenger_rating'] + df['driver_rating']) / 2

# Reorder columns
df = df[['ride_id', 'pickup_time', 'ride_duration_minutes', 'distance_km',
         'total_fare', 'surge_multiplier', 'vehicle_type', 'payment_method',
         'passenger_rating', 'driver_rating', 'ride_rating', 'hour',
         'day_of_week', 'date', 'is_cancelled']]

print(f"\nDataset created with {len(df)} rides")
print(f"Date range: {df['pickup_time'].min().date()} to {df['pickup_time'].max().date()}")

# ============================================================
# 1. EXPLORATORY DATA ANALYSIS (EDA)
# ============================================================
print("\n" + "=" * 60)
print("1. EXPLORATORY DATA ANALYSIS")
print("=" * 60)

print("\n📊 Dataset Overview:")
print(df.head(10))

print("\n📈 Dataset Shape and Info:")
print(f"Total Rides: {len(df)}")
print(f"Columns: {df.shape[1]}")
print(f"\nData Types:\n{df.dtypes}")

print("\n📉 Statistical Summary:")
print(df.describe().round(2))

print("\n🔍 Missing Values:")
print(df.isnull().sum())

print("\n✅ Data Quality Check:")
print(f"Cancelled Rides: {df['is_cancelled'].sum()} ({(df['is_cancelled'].sum()/len(df)*100):.2f}%)")
print(f"Completed Rides: {(~df['is_cancelled'].astype(bool)).sum()} ({((~df['is_cancelled'].astype(bool)).sum()/len(df)*100):.2f}%)")

# ============================================================
# 2. KEY METRICS & INSIGHTS
# ============================================================
print("\n" + "=" * 60)
print("2. KEY METRICS & INSIGHTS")
print("=" * 60)

# Filter completed rides for analysis
completed_rides = df[df['is_cancelled'] == 0]

print(f"\n💰 Revenue Metrics:")
total_revenue = completed_rides['total_fare'].sum()
avg_fare = completed_rides['total_fare'].mean()
median_fare = completed_rides['total_fare'].median()
print(f"Total Revenue: ${total_revenue:,.2f}")
print(f"Average Fare: ${avg_fare:.2f}")
print(f"Median Fare: ${median_fare:.2f}")
print(f"Min Fare: ${completed_rides['total_fare'].min():.2f}")
print(f"Max Fare: ${completed_rides['total_fare'].max():.2f}")

print(f"\n🚗 Trip Metrics:")
print(f"Average Distance: {completed_rides['distance_km'].mean():.2f} km")
print(f"Average Duration: {completed_rides['ride_duration_minutes'].mean():.2f} minutes")
print(f"Average Speed: {(completed_rides['distance_km'].mean() / completed_rides['ride_duration_minutes'].mean() * 60):.2f} km/h")

print(f"\n⭐ Rating Metrics:")
print(f"Average Passenger Rating: {completed_rides['passenger_rating'].mean():.2f}/5")
print(f"Average Driver Rating: {completed_rides['driver_rating'].mean():.2f}/5")
print(f"Average Ride Rating: {completed_rides['ride_rating'].mean():.2f}/5")

print(f"\n🚕 Vehicle Type Distribution:")
vehicle_dist = df['vehicle_type'].value_counts()
for vtype, count in vehicle_dist.items():
    print(f"  {vtype}: {count} ({count/len(df)*100:.1f}%)")

print(f"\n💳 Payment Method Distribution:")
payment_dist = df['payment_method'].value_counts()
for pmethod, count in payment_dist.items():
    print(f"  {pmethod}: {count} ({count/len(df)*100:.1f}%)")

# ============================================================
# 3. VISUALIZATIONS
# ============================================================
print("\n" + "=" * 60)
print("3. CREATING VISUALIZATIONS")
print("=" * 60)

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
fig.suptitle('Ride-Sharing Data Analysis Dashboard', fontsize=16, fontweight='bold')

# 1. Fare Distribution
axes[0, 0].hist(completed_rides['total_fare'], bins=50, color='skyblue', edgecolor='black')
axes[0, 0].set_title('Distribution of Fares', fontweight='bold')
axes[0, 0].set_xlabel('Total Fare ($)')
axes[0, 0].set_ylabel('Frequency')
axes[0, 0].axvline(avg_fare, color='red', linestyle='--', label=f'Mean: ${avg_fare:.2f}')
axes[0, 0].legend()

# 2. Distance vs Fare
scatter = axes[0, 1].scatter(completed_rides['distance_km'], completed_rides['total_fare'],
                             c=completed_rides['surge_multiplier'], cmap='viridis', alpha=0.6)
axes[0, 1].set_title('Distance vs Fare (colored by Surge)', fontweight='bold')
axes[0, 1].set_xlabel('Distance (km)')
axes[0, 1].set_ylabel('Total Fare ($)')
plt.colorbar(scatter, ax=axes[0, 1], label='Surge Multiplier')

# 3. Vehicle Type vs Average Fare
vehicle_fare = completed_rides.groupby('vehicle_type')['total_fare'].mean().sort_values(ascending=False)
axes[0, 2].bar(vehicle_fare.index, vehicle_fare.values, color=['#FF6B6B', '#4ECDC4', '#45B7D1'])
axes[0, 2].set_title('Average Fare by Vehicle Type', fontweight='bold')
axes[0, 2].set_ylabel('Average Fare ($)')
for i, v in enumerate(vehicle_fare.values):
    axes[0, 2].text(i, v + 0.5, f'${v:.2f}', ha='center')

# 4. Rides by Hour of Day
rides_by_hour = completed_rides.groupby('hour').size()
axes[1, 0].plot(rides_by_hour.index, rides_by_hour.values, marker='o', color='#FF6B6B', linewidth=2)
axes[1, 0].fill_between(rides_by_hour.index, rides_by_hour.values, alpha=0.3, color='#FF6B6B')
axes[1, 0].set_title('Rides by Hour of Day', fontweight='bold')
axes[1, 0].set_xlabel('Hour of Day')
axes[1, 0].set_ylabel('Number of Rides')
axes[1, 0].grid(True, alpha=0.3)

# 5. Rating Distribution
axes[1, 1].hist(completed_rides['ride_rating'], bins=30, color='#4ECDC4', edgecolor='black')
axes[1, 1].set_title('Distribution of Ride Ratings', fontweight='bold')
axes[1, 1].set_xlabel('Rating (1-5)')
axes[1, 1].set_ylabel('Frequency')
axes[1, 1].axvline(completed_rides['ride_rating'].mean(), color='red',
                   linestyle='--', label=f"Mean: {completed_rides['ride_rating'].mean():.2f}")
axes[1, 1].legend()

# 6. Payment Method Distribution
payment_counts = df['payment_method'].value_counts()
colors = ['#FF6B6B', '#4ECDC4', '#45B7D1']
axes[1, 2].pie(payment_counts.values, labels=payment_counts.index, autopct='%1.1f%%',
               colors=colors, startangle=90)
axes[1, 2].set_title('Payment Method Distribution', fontweight='bold')

plt.tight_layout()
plt.show()

print("✅ Dashboard created successfully!")

# ============================================================
# 4. ADVANCED ANALYSIS
# ============================================================
print("\n" + "=" * 60)
print("4. ADVANCED ANALYSIS")
print("=" * 60)

# 4.1 Peak Hours Analysis
print("\n🔴 Peak Hours Analysis:")
rides_by_hour_df = completed_rides.groupby('hour').agg({
    'ride_id': 'count',
    'total_fare': ['mean', 'sum']
}).round(2)
rides_by_hour_df.columns = ['Rides', 'Avg Fare', 'Total Revenue']
print("\nRides by Hour of Day:")
print(rides_by_hour_df.head(10))

# 4.2 Day of Week Analysis
print("\n📅 Day of Week Analysis:")
day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
day_analysis = completed_rides.groupby('day_of_week').agg({
    'ride_id': 'count',
    'total_fare': 'mean',
    'ride_rating': 'mean'
}).reindex(day_order)
day_analysis.columns = ['Rides', 'Avg Fare', 'Avg Rating']
print(day_analysis.round(2))

# 4.3 Surge Pricing Impact
print("\n⚡ Surge Pricing Impact:")
surge_analysis = completed_rides.groupby('surge_multiplier').agg({
    'ride_id': 'count',
    'total_fare': 'mean',
    'distance_km': 'mean'
}).round(2)
surge_analysis.columns = ['Number of Rides', 'Avg Fare', 'Avg Distance']
print(surge_analysis)

# 4.4 Rating Correlation
print("\n📊 Correlation Analysis:")
correlation_columns = ['ride_duration_minutes', 'distance_km', 'total_fare',
                      'passenger_rating', 'driver_rating', 'surge_multiplier']
corr_matrix = completed_rides[correlation_columns].corr()
print("\nCorrelation Matrix (selected variables):")
print(corr_matrix.round(3))

# ============================================================
# 5. ADVANCED VISUALIZATIONS
# ============================================================
print("\n" + "=" * 60)
print("5. CREATING ADVANCED VISUALIZATIONS")
print("=" * 60)

fig, axes = plt.subplots(2, 2, figsize=(16, 12))
fig.suptitle('Advanced Ride-Sharing Analysis', fontsize=16, fontweight='bold')

# 1. Heatmap of rides by hour and day
pivot_data = completed_rides.groupby(['day_of_week', 'hour']).size().unstack(fill_value=0)
pivot_data = pivot_data.reindex(day_order)
sns.heatmap(pivot_data, cmap='YlOrRd', ax=axes[0, 0], cbar_kws={'label': 'Number of Rides'})
axes[0, 0].set_title('Ride Frequency: Hour x Day of Week Heatmap', fontweight='bold')
axes[0, 0].set_ylabel('Day of Week')
axes[0, 0].set_xlabel('Hour of Day')

# 2. Rating vs Fare
axes[0, 1].scatter(completed_rides['total_fare'], completed_rides['ride_rating'],
                   alpha=0.5, color='#4ECDC4')
z = np.polyfit(completed_rides['total_fare'], completed_rides['ride_rating'], 1)
p = np.poly1d(z)
axes[0, 1].plot(completed_rides['total_fare'].sort_values(),
                p(completed_rides['total_fare'].sort_values()),
                "r--", alpha=0.8, label='Trend Line')
axes[0, 1].set_title('Rating vs Fare Amount', fontweight='bold')
axes[0, 1].set_xlabel('Total Fare ($)')
axes[0, 1].set_ylabel('Rating (1-5)')
axes[0, 1].legend()

# 3. Box plot of fares by vehicle type
completed_rides.boxplot(column='total_fare', by='vehicle_type', ax=axes[1, 0])
axes[1, 0].set_title('Fare Distribution by Vehicle Type', fontweight='bold')
axes[1, 0].set_xlabel('Vehicle Type')
axes[1, 0].set_ylabel('Total Fare ($)')
plt.sca(axes[1, 0])
plt.xticks(rotation=0)

# 4. Revenue trend over time
daily_revenue = completed_rides.groupby('date').agg({
    'total_fare': 'sum',
    'ride_id': 'count'
}).sort_index()
daily_revenue.columns = ['Revenue', 'Rides']

ax_revenue = axes[1, 1]
ax_rides = ax_revenue.twinx()

ax_revenue.plot(daily_revenue.index, daily_revenue['Revenue'], color='#FF6B6B',
                marker='o', label='Revenue', linewidth=2)
ax_rides.plot(daily_revenue.index, daily_revenue['Rides'], color='#4ECDC4',
              marker='s', label='Rides', linewidth=2, alpha=0.7)

ax_revenue.set_title('Daily Revenue and Ride Count Trend', fontweight='bold')
ax_revenue.set_xlabel('Date')
ax_revenue.set_ylabel('Daily Revenue ($)', color='#FF6B6B')
ax_rides.set_ylabel('Number of Rides', color='#4ECDC4')
ax_revenue.tick_params(axis='y', labelcolor='#FF6B6B')
ax_rides.tick_params(axis='y', labelcolor='#4ECDC4')
ax_revenue.grid(True, alpha=0.3)

fig.tight_layout()
plt.show()

print("✅ Advanced visualizations created!")

# ============================================================
# 6. PREDICTIVE INSIGHTS
# ============================================================
print("\n" + "=" * 60)
print("6. PREDICTIVE INSIGHTS & RECOMMENDATIONS")
print("=" * 60)

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# Prepare data for clustering
X = completed_rides[['distance_km', 'ride_duration_minutes', 'total_fare', 'ride_rating']].copy()
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Perform K-means clustering
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
completed_rides['cluster'] = kmeans.fit_predict(X_scaled)

print("\n🎯 Customer Segmentation (K-Means Clustering):")
for cluster_id in range(3):
    cluster_data = completed_rides[completed_rides['cluster'] == cluster_id]
    print(f"\nCluster {cluster_id + 1} ({len(cluster_data)} rides):")
    print(f"  Avg Distance: {cluster_data['distance_km'].mean():.2f} km")
    print(f"  Avg Fare: ${cluster_data['total_fare'].mean():.2f}")
    print(f"  Avg Rating: {cluster_data['ride_rating'].mean():.2f}/5")
    print(f"  Avg Duration: {cluster_data['ride_duration_minutes'].mean():.2f} min")

# Calculate efficiency metrics
print("\n📈 Efficiency Metrics:")
avg_revenue_per_minute = completed_rides['total_fare'].sum() / completed_rides['ride_duration_minutes'].sum()
avg_revenue_per_km = completed_rides['total_fare'].sum() / completed_rides['distance_km'].sum()
print(f"Revenue per Minute: ${avg_revenue_per_minute:.2f}")
print(f"Revenue per KM: ${avg_revenue_per_km:.2f}")

# Calculate cancellation rate impact
print("\n❌ Cancellation Impact Analysis:")
print(f"Total Cancellations: {df['is_cancelled'].sum()}")
print(f"Cancellation Rate: {(df['is_cancelled'].sum()/len(df)*100):.2f}%")
print(f"Lost Revenue (Est.): ${df[df['is_cancelled']==1]['total_fare'].sum():.2f}")

# ============================================================
# 7. RECOMMENDATIONS
# ============================================================
print("\n" + "=" * 60)
print("7. KEY RECOMMENDATIONS")
print("=" * 60)

recommendations = [
    "1. Focus on Peak Hours: Concentrate driver incentives during 7-9 AM and 5-7 PM",
    "2. Premium Service Strategy: Premium vehicles command 20-30% higher fares",
    "3. Surge Pricing: Apply surge multipliers strategically on weekends (Sat-Sun)",
    "4. Quality Control: Rides with ratings < 3.5 need investigation",
    "5. Cancellation Reduction: Target reducing cancellation rate from 5% to 2%",
    "6. Long Distance Trips: Longer trips show higher customer satisfaction (4.5+ rating)",
    "7. Payment Methods: Promote digital payments (Card/Wallet) - 85% adoption",
    "8. Revenue Optimization: Target average fare growth from $12 to $15 per ride"
]

for rec in recommendations:
    print(f"  {rec}")

# ============================================================
# 8. EXPORT RESULTS
# ============================================================
print("\n" + "=" * 60)
print("8. DATA EXPORT")
print("=" * 60)

# Save the analysis dataset
csv_path = 'ride_sharing_analysis.csv'
df.to_csv(csv_path, index=False)
print(f"✅ Full dataset saved to: {csv_path}")

# Create summary statistics
summary_stats = {
    'Metric': [
        'Total Rides',
        'Completed Rides',
        'Cancellation Rate',
        'Total Revenue',
        'Average Fare',
        'Average Distance (km)',
        'Average Duration (min)',
        'Average Rating',
        'Peak Hour',
        'Busiest Day'
    ],
    'Value': [
        len(df),
        len(completed_rides),
        f"{(df['is_cancelled'].sum()/len(df)*100):.2f}%",
        f"${total_revenue:,.2f}",
        f"${avg_fare:.2f}",
        f"{completed_rides['distance_km'].mean():.2f}",
        f"{completed_rides['ride_duration_minutes'].mean():.2f}",
        f"{completed_rides['ride_rating'].mean():.2f}/5",
        f"{rides_by_hour.idxmax()}:00 - {rides_by_hour.idxmax()+1}:00",
        day_analysis['Rides'].idxmax()
    ]
}

summary_df = pd.DataFrame(summary_stats)
summary_csv_path = 'analysis_summary.csv'
summary_df.to_csv(summary_csv_path, index=False)
print(f"✅ Summary statistics saved to: {summary_csv_path}")

print("\n" + "=" * 60)
print("ANALYSIS COMPLETE!")
print("=" * 60)
print("\n📌 Next Steps:")
print("  1. Download the CSV files for further analysis")
print("  2. Share findings with stakeholders")
print("  3. Implement recommendations")
print("  4. Monitor KPIs regularly")

"""## 9. DEEP LEARNING MODELING (Simple Neural Network for Fare Prediction)"""

import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

print("TensorFlow Version:", tf.__version__)

"""### 9.1 Data Preparation for Deep Learning

We'll prepare the `completed_rides` data for a regression task to predict `total_fare` using numerical features. Categorical features will need to be one-hot encoded.
"""

features = ['distance_km', 'ride_duration_minutes', 'surge_multiplier', 'passenger_rating', 'driver_rating', 'hour', 'vehicle_type', 'day_of_week']
target = 'total_fare'

X = completed_rides[features].copy()
y = completed_rides[target].copy()

# One-hot encode categorical features
X = pd.get_dummies(X, columns=['vehicle_type', 'day_of_week'], drop_first=True)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale numerical features
scaler_nn = StandardScaler()
X_train_scaled = scaler_nn.fit_transform(X_train)
X_test_scaled = scaler_nn.transform(X_test)

print(f"X_train shape: {X_train_scaled.shape}")
print(f"X_test shape: {X_test_scaled.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

"""### 9.2 Define and Train the Deep Learning Model

We'll create a simple feed-forward neural network using TensorFlow/Keras.
"""

model = tf.keras.Sequential([
    tf.keras.layers.Dense(128, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1) # Output layer for regression
])

model.compile(optimizer='adam', loss='mean_squared_error')

print("Model Summary:")
model.summary()

history = model.fit(
    X_train_scaled, y_train,
    epochs=50,
    batch_size=32,
    validation_split=0.2,
    verbose=0 # Suppress output for cleaner notebook
)

print("\nModel training complete.")

"""### 9.3 Evaluate the Deep Learning Model

Let's evaluate the model's performance on the test set.
"""

y_pred_nn = model.predict(X_test_scaled).flatten()

mse_nn = mean_squared_error(y_test, y_pred_nn)
rmse_nn = np.sqrt(mse_nn)
r2_nn = r2_score(y_test, y_pred_nn)

print(f"Mean Squared Error (NN): {mse_nn:.2f}")
print(f"Root Mean Squared Error (NN): {rmse_nn:.2f}")
print(f"R-squared (NN): {r2_nn:.2f}")

# Visualize predictions vs actuals
plt.figure(figsize=(10, 6))
plt.scatter(y_test, y_pred_nn, alpha=0.3)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
plt.xlabel('Actual Fare')
plt.ylabel('Predicted Fare')
plt.title('Deep Learning Model: Actual vs Predicted Fares')
plt.grid(True)
plt.show()

"""
RIDE-SHARING DATA ANALYSIS - LOCAL PROTOTYPE
=============================================
A complete stand-alone project to run on your computer
Run with: python ride_sharing_local.py
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import warnings
warnings.filterwarnings('ignore')

# ============================================================
# SETUP - CREATE OUTPUT DIRECTORY
# ============================================================
OUTPUT_DIR = "ride_sharing_results"
if not os.path.exists(OUTPUT_DIR):
    os.makedirs(OUTPUT_DIR)
    print(f"✅ Created output directory: {OUTPUT_DIR}")

# Set style for better visualizations
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (14, 6)

# ============================================================
# BANNER
# ============================================================
print("\n" + "="*70)
print(" " * 15 + "🚗 RIDE-SHARING DATA ANALYSIS 🚗")
print(" " * 20 + "LOCAL PROTOTYPE v1.0")
print("="*70 + "\n")

# ============================================================
# CREATE SAMPLE RIDE-SHARING DATASET
# ============================================================
print("📊 STEP 1: CREATING SAMPLE DATASET...")
print("-" * 70)

np.random.seed(42)

# Generate synthetic ride data
n_rides = 5000
print(f"Generating {n_rides} ride records...\n")

data = {
    'ride_id': np.arange(1, n_rides + 1),
    'pickup_time': [datetime.now() - timedelta(days=np.random.randint(0, 365)) for _ in range(n_rides)],
    'ride_duration_minutes': np.random.gamma(shape=2, scale=15, size=n_rides),
    'distance_km': np.random.gamma(shape=2, scale=5, size=n_rides),
    'base_fare': np.random.uniform(2, 5, n_rides),
    'distance_fare': np.random.uniform(1, 3, n_rides),
    'surge_multiplier': np.random.choice([1.0, 1.5, 2.0, 2.5], n_rides, p=[0.7, 0.15, 0.1, 0.05]),
    'passenger_rating': np.random.uniform(1, 5, n_rides),
    'driver_rating': np.random.uniform(1, 5, n_rides),
    'vehicle_type': np.random.choice(['Economy', 'Comfort', 'Premium'], n_rides, p=[0.6, 0.3, 0.1]),
    'payment_method': np.random.choice(['Card', 'Cash', 'Wallet'], n_rides, p=[0.7, 0.15, 0.15]),
    'is_cancelled': np.random.choice([0, 1], n_rides, p=[0.95, 0.05]),
}

df = pd.DataFrame(data)

# Calculate total fare
df['total_fare'] = (df['base_fare'] + df['distance_fare'] * df['distance_km']) * df['surge_multiplier']

# Add time features
df['hour'] = df['pickup_time'].dt.hour
df['day_of_week'] = df['pickup_time'].dt.day_name()
df['date'] = df['pickup_time'].dt.date

# Calculate ride rating
df['ride_rating'] = (df['passenger_rating'] + df['driver_rating']) / 2

# Reorder columns
df = df[['ride_id', 'pickup_time', 'ride_duration_minutes', 'distance_km',
         'total_fare', 'surge_multiplier', 'vehicle_type', 'payment_method',
         'passenger_rating', 'driver_rating', 'ride_rating', 'hour',
         'day_of_week', 'date', 'is_cancelled']]

print(f"✅ Dataset created with {len(df):,} rides")
print(f"📅 Date range: {df['pickup_time'].min().date()} to {df['pickup_time'].max().date()}\n")

# ============================================================
# EXPLORATORY DATA ANALYSIS
# ============================================================
print("📈 STEP 2: EXPLORATORY DATA ANALYSIS")
print("-" * 70)

print("\n📋 First 10 Rows:")
print(df.head(10).to_string())

print("\n\n📊 Dataset Info:")
print(f"Total Rides: {len(df):,}")
print(f"Columns: {df.shape[1]}")
print(f"Data Types:")
for col, dtype in df.dtypes.items():
    print(f"  • {col}: {dtype}")

print("\n📉 Statistical Summary:")
print(df.describe().round(2).to_string())

print("\n🔍 Missing Values:")
missing = df.isnull().sum()
print(f"Total missing values: {missing.sum()}")

print("\n✅ Data Quality:")
cancelled_count = df['is_cancelled'].sum()
completed_count = len(df) - cancelled_count
print(f"  Cancelled Rides: {cancelled_count} ({(cancelled_count/len(df)*100):.2f}%)")
print(f"  Completed Rides: {completed_count} ({(completed_count/len(df)*100):.2f}%)\n")

# ============================================================
# KEY METRICS & INSIGHTS
# ============================================================
print("\n💰 STEP 3: KEY METRICS & INSIGHTS")
print("-" * 70)

# Filter completed rides
completed_rides = df[df['is_cancelled'] == 0]

print("\n💵 REVENUE METRICS:")
total_revenue = completed_rides['total_fare'].sum()
avg_fare = completed_rides['total_fare'].mean()
median_fare = completed_rides['total_fare'].median()
min_fare = completed_rides['total_fare'].min()
max_fare = completed_rides['total_fare'].max()

print(f"  Total Revenue:        ${total_revenue:>12,.2f}")
print(f"  Average Fare:         ${avg_fare:>12,.2f}")
print(f"  Median Fare:          ${median_fare:>12,.2f}")
print(f"  Min Fare:             ${min_fare:>12,.2f}")
print(f"  Max Fare:             ${max_fare:>12,.2f}")

print("\n🚗 TRIP METRICS:")
avg_distance = completed_rides['distance_km'].mean()
avg_duration = completed_rides['ride_duration_minutes'].mean()
avg_speed = (avg_distance / avg_duration * 60)

print(f"  Average Distance:     {avg_distance:>12,.2f} km")
print(f"  Average Duration:     {avg_duration:>12,.2f} minutes")
print(f"  Average Speed:        {avg_speed:>12,.2f} km/h")

print("\n⭐ RATING METRICS:")
print(f"  Avg Passenger Rating: {completed_rides['passenger_rating'].mean():>12,.2f} / 5")
print(f"  Avg Driver Rating:    {completed_rides['driver_rating'].mean():>12,.2f} / 5")
print(f"  Avg Overall Rating:   {completed_rides['ride_rating'].mean():>12,.2f} / 5")

print("\n🚕 VEHICLE TYPE DISTRIBUTION:")
vehicle_dist = df['vehicle_type'].value_counts()
for vtype in ['Economy', 'Comfort', 'Premium']:
    count = vehicle_dist.get(vtype, 0)
    pct = (count/len(df)*100)
    print(f"  {vtype:<10} {count:>6} rides ({pct:>5.1f}%)")

print("\n💳 PAYMENT METHOD DISTRIBUTION:")
payment_dist = df['payment_method'].value_counts()
for pmethod in ['Card', 'Cash', 'Wallet']:
    count = payment_dist.get(pmethod, 0)
    pct = (count/len(df)*100)
    print(f"  {pmethod:<10} {count:>6} rides ({pct:>5.1f}%)\n")

# ============================================================
# SAVE FULL DATASET
# ============================================================
csv_path = os.path.join(OUTPUT_DIR, 'ride_sharing_data.csv')
df.to_csv(csv_path, index=False)
print(f"✅ Full dataset saved: {csv_path}")

# ============================================================
# VISUALIZATION 1: MAIN DASHBOARD
# ============================================================
print("\n\n📊 STEP 4: CREATING VISUALIZATIONS")
print("-" * 70)
print("Creating Dashboard 1: Main Analysis...")

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
fig.suptitle('Ride-Sharing Data Analysis Dashboard', fontsize=16, fontweight='bold')

# 1. Fare Distribution
axes[0, 0].hist(completed_rides['total_fare'], bins=50, color='skyblue', edgecolor='black')
axes[0, 0].set_title('Distribution of Fares', fontweight='bold')
axes[0, 0].set_xlabel('Total Fare ($)')
axes[0, 0].set_ylabel('Frequency')
axes[0, 0].axvline(avg_fare, color='red', linestyle='--', linewidth=2, label=f'Mean: ${avg_fare:.2f}')
axes[0, 0].legend()
axes[0, 0].grid(True, alpha=0.3)

# 2. Distance vs Fare
scatter = axes[0, 1].scatter(completed_rides['distance_km'], completed_rides['total_fare'],
                             c=completed_rides['surge_multiplier'], cmap='viridis', alpha=0.6, s=30)
axes[0, 1].set_title('Distance vs Fare (colored by Surge)', fontweight='bold')
axes[0, 1].set_xlabel('Distance (km)')
axes[0, 1].set_ylabel('Total Fare ($)')
cbar = plt.colorbar(scatter, ax=axes[0, 1])
cbar.set_label('Surge Multiplier')

# 3. Vehicle Type vs Average Fare
vehicle_fare = completed_rides.groupby('vehicle_type')['total_fare'].mean().sort_values(ascending=False)
colors_vehicle = ['#FF6B6B', '#4ECDC4', '#45B7D1']
bars = axes[0, 2].bar(vehicle_fare.index, vehicle_fare.values, color=colors_vehicle, edgecolor='black')
axes[0, 2].set_title('Average Fare by Vehicle Type', fontweight='bold')
axes[0, 2].set_ylabel('Average Fare ($)')
axes[0, 2].grid(True, alpha=0.3, axis='y')
for bar in bars:
    height = bar.get_height()
    axes[0, 2].text(bar.get_x() + bar.get_width()/2., height,
                    f'${height:.2f}', ha='center', va='bottom', fontweight='bold')

# 4. Rides by Hour of Day
rides_by_hour = completed_rides.groupby('hour').size()
axes[1, 0].plot(rides_by_hour.index, rides_by_hour.values, marker='o', color='#FF6B6B',
                linewidth=2, markersize=6)
axes[1, 0].fill_between(rides_by_hour.index, rides_by_hour.values, alpha=0.3, color='#FF6B6B')
axes[1, 0].set_title('Rides by Hour of Day', fontweight='bold')
axes[1, 0].set_xlabel('Hour of Day')
axes[1, 0].set_ylabel('Number of Rides')
axes[1, 0].grid(True, alpha=0.3)

# 5. Rating Distribution
axes[1, 1].hist(completed_rides['ride_rating'], bins=30, color='#4ECDC4', edgecolor='black')
axes[1, 1].set_title('Distribution of Ride Ratings', fontweight='bold')
axes[1, 1].set_xlabel('Rating (1-5)')
axes[1, 1].set_ylabel('Frequency')
axes[1, 1].axvline(completed_rides['ride_rating'].mean(), color='red', linestyle='--',
                   linewidth=2, label=f"Mean: {completed_rides['ride_rating'].mean():.2f}")
axes[1, 1].legend()
axes[1, 1].grid(True, alpha=0.3)

# 6. Payment Method Distribution
payment_counts = df['payment_method'].value_counts()
colors_payment = ['#FF6B6B', '#4ECDC4', '#45B7D1']
wedges, texts, autotexts = axes[1, 2].pie(payment_counts.values, labels=payment_counts.index,
                                            autopct='%1.1f%%', colors=colors_payment, startangle=90)
axes[1, 2].set_title('Payment Method Distribution', fontweight='bold')
for autotext in autotexts:
    autotext.set_color('white')
    autotext.set_fontweight('bold')

plt.tight_layout()
dashboard1_path = os.path.join(OUTPUT_DIR, 'dashboard_1_main_analysis.png')
plt.savefig(dashboard1_path, dpi=300, bbox_inches='tight')
print(f"✅ Dashboard 1 saved: {dashboard1_path}")
plt.close()

# ============================================================
# VISUALIZATION 2: ADVANCED ANALYSIS
# ============================================================
print("Creating Dashboard 2: Advanced Analysis...")

fig, axes = plt.subplots(2, 2, figsize=(16, 12))
fig.suptitle('Advanced Ride-Sharing Analysis', fontsize=16, fontweight='bold')

# 1. Heatmap of rides by hour and day
day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
pivot_data = completed_rides.groupby(['day_of_week', 'hour']).size().unstack(fill_value=0)
pivot_data = pivot_data.reindex(day_order)
sns.heatmap(pivot_data, cmap='YlOrRd', ax=axes[0, 0], cbar_kws={'label': 'Number of Rides'})
axes[0, 0].set_title('Ride Frequency: Hour x Day of Week Heatmap', fontweight='bold')
axes[0, 0].set_ylabel('Day of Week')
axes[0, 0].set_xlabel('Hour of Day')

# 2. Rating vs Fare
axes[0, 1].scatter(completed_rides['total_fare'], completed_rides['ride_rating'],
                   alpha=0.5, color='#4ECDC4', s=30)
z = np.polyfit(completed_rides['total_fare'], completed_rides['ride_rating'], 1)
p = np.poly1d(z)
sorted_fares = completed_rides['total_fare'].sort_values()
axes[0, 1].plot(sorted_fares, p(sorted_fares), "r--", alpha=0.8, linewidth=2, label='Trend Line')
axes[0, 1].set_title('Rating vs Fare Amount', fontweight='bold')
axes[0, 1].set_xlabel('Total Fare ($)')
axes[0, 1].set_ylabel('Rating (1-5)')
axes[0, 1].legend()
axes[0, 1].grid(True, alpha=0.3)

# 3. Box plot of fares by vehicle type
vehicle_order = ['Economy', 'Comfort', 'Premium']
completed_rides_temp = completed_rides.copy()
axes[1, 0].boxplot([completed_rides_temp[completed_rides_temp['vehicle_type'] == vtype]['total_fare']
                    for vtype in vehicle_order],
                   labels=vehicle_order)
axes[1, 0].set_title('Fare Distribution by Vehicle Type', fontweight='bold')
axes[1, 0].set_ylabel('Total Fare ($)')
axes[1, 0].grid(True, alpha=0.3, axis='y')

# 4. Revenue trend over time
daily_revenue = completed_rides.groupby('date').agg({
    'total_fare': 'sum',
    'ride_id': 'count'
}).sort_index()

ax_revenue = axes[1, 1]
ax_rides = ax_revenue.twinx()

ax_revenue.plot(daily_revenue.index, daily_revenue['total_fare'], color='#FF6B6B',
                marker='o', label='Daily Revenue', linewidth=2, markersize=5)
ax_rides.plot(daily_revenue.index, daily_revenue['ride_id'], color='#4ECDC4',
              marker='s', label='Daily Rides', linewidth=2, alpha=0.7, markersize=5)

ax_revenue.set_title('Daily Revenue and Ride Count Trend', fontweight='bold')
ax_revenue.set_xlabel('Date')
ax_revenue.set_ylabel('Daily Revenue ($)', color='#FF6B6B', fontweight='bold')
ax_rides.set_ylabel('Number of Rides', color='#4ECDC4', fontweight='bold')
ax_revenue.tick_params(axis='y', labelcolor='#FF6B6B')
ax_rides.tick_params(axis='y', labelcolor='#4ECDC4')
ax_revenue.grid(True, alpha=0.3)

fig.tight_layout()
dashboard2_path = os.path.join(OUTPUT_DIR, 'dashboard_2_advanced_analysis.png')
plt.savefig(dashboard2_path, dpi=300, bbox_inches='tight')
print(f"✅ Dashboard 2 saved: {dashboard2_path}")
plt.close()

# ============================================================
# DETAILED ANALYSIS REPORTS
# ============================================================
print("\nGenerating detailed analysis reports...")

# Peak Hours Analysis
print("\n\n🔴 PEAK HOURS ANALYSIS")
print("-" * 70)
rides_by_hour_df = completed_rides.groupby('hour').agg({
    'ride_id': 'count',
    'total_fare': ['mean', 'sum']
}).round(2)
rides_by_hour_df.columns = ['Rides', 'Avg Fare', 'Total Revenue']
print("\nTop 5 Peak Hours:")
print(rides_by_hour_df.nlargest(5, 'Rides').to_string())

peak_hour = rides_by_hour_df['Rides'].idxmax()
peak_rides = rides_by_hour_df.loc[peak_hour, 'Rides']
print(f"\n🔥 BUSIEST HOUR: {peak_hour}:00 with {int(peak_rides)} rides")

# Day of Week Analysis
print("\n\n📅 DAY OF WEEK ANALYSIS")
print("-" * 70)
day_analysis = completed_rides.groupby('day_of_week').agg({
    'ride_id': 'count',
    'total_fare': 'mean',
    'ride_rating': 'mean'
}).reindex(day_order)
day_analysis.columns = ['Rides', 'Avg Fare', 'Avg Rating']
print("\n")
print(day_analysis.round(2).to_string())

busiest_day = day_analysis['Rides'].idxmax()
print(f"\n📈 BUSIEST DAY: {busiest_day} with {int(day_analysis.loc[busiest_day, 'Rides'])} rides")

# Surge Pricing Analysis
print("\n\n⚡ SURGE PRICING IMPACT")
print("-" * 70)
surge_analysis = completed_rides.groupby('surge_multiplier').agg({
    'ride_id': 'count',
    'total_fare': 'mean',
    'distance_km': 'mean'
}).round(2)
surge_analysis.columns = ['Number of Rides', 'Avg Fare', 'Avg Distance']
print("\n")
print(surge_analysis.to_string())

# Correlation Analysis
print("\n\n📊 CORRELATION ANALYSIS")
print("-" * 70)
correlation_columns = ['ride_duration_minutes', 'distance_km', 'total_fare',
                      'passenger_rating', 'driver_rating', 'surge_multiplier']
corr_matrix = completed_rides[correlation_columns].corr()
print("\nCorrelation Matrix:")
print(corr_matrix.round(3).to_string())

# ============================================================
# CUSTOMER SEGMENTATION
# ============================================================
print("\n\n🎯 CUSTOMER SEGMENTATION (K-MEANS CLUSTERING)")
print("-" * 70)

X = completed_rides[['distance_km', 'ride_duration_minutes', 'total_fare', 'ride_rating']].copy()
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
completed_rides['cluster'] = kmeans.fit_predict(X_scaled)

for cluster_id in range(3):
    cluster_data = completed_rides[completed_rides['cluster'] == cluster_id]
    print(f"\n{'─'*50}")
    print(f"CLUSTER {cluster_id + 1} - {len(cluster_data)} rides ({len(cluster_data)/len(completed_rides)*100:.1f}%)")
    print(f"{'─'*50}")
    print(f"  Avg Distance:      {cluster_data['distance_km'].mean():>8.2f} km")
    print(f"  Avg Fare:          ${cluster_data['total_fare'].mean():>7.2f}")
    print(f"  Avg Rating:        {cluster_data['ride_rating'].mean():>8.2f} / 5")
    print(f"  Avg Duration:      {cluster_data['ride_duration_minutes'].mean():>8.2f} minutes")

    # Determine cluster name
    avg_fare_cluster = cluster_data['total_fare'].mean()
    if cluster_id == 0:
        cluster_type = "SHORT TRIPS (Budget)"
    elif cluster_id == 1:
        cluster_type = "LONG TRIPS (Premium)"
    else:
        cluster_type = "STANDARD TRIPS (Regular)"
    print(f"  Cluster Type:      {cluster_type}")

# ============================================================
# CREATE COMPREHENSIVE REPORT
# ============================================================
print("\n\n📋 CREATING COMPREHENSIVE REPORT")
print("-" * 70)

report_text = f"""
{'='*70}
RIDE-SHARING DATA ANALYSIS REPORT
{'='*70}

REPORT GENERATED: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

{'='*70}
EXECUTIVE SUMMARY
{'='*70}

Dataset Overview:
  • Total Records: {len(df):,}
  • Completed Rides: {len(completed_rides):,}
  • Cancelled Rides: {df['is_cancelled'].sum()} ({(df['is_cancelled'].sum()/len(df)*100):.2f}%)
  • Date Range: {df['pickup_time'].min().date()} to {df['pickup_time'].max().date()}

Key Revenue Metrics:
  • Total Revenue: ${total_revenue:,.2f}
  • Average Fare: ${avg_fare:.2f}
  • Median Fare: ${median_fare:.2f}
  • Revenue Range: ${min_fare:.2f} - ${max_fare:.2f}

Trip Performance:
  • Average Distance: {avg_distance:.2f} km
  • Average Duration: {avg_duration:.2f} minutes
  • Average Speed: {avg_speed:.2f} km/h
  • Revenue per KM: ${completed_rides['total_fare'].sum() / completed_rides['distance_km'].sum():.2f}
  • Revenue per Minute: ${completed_rides['total_fare'].sum() / completed_rides['ride_duration_minutes'].sum():.2f}

Quality Metrics:
  • Average Passenger Rating: {completed_rides['passenger_rating'].mean():.2f} / 5
  • Average Driver Rating: {completed_rides['driver_rating'].mean():.2f} / 5
  • Average Overall Rating: {completed_rides['ride_rating'].mean():.2f} / 5

{'='*70}
DEMAND PATTERNS
{'='*70}

Peak Hour: {peak_hour}:00 ({int(peak_rides)} rides)
Busiest Day: {busiest_day}

Hourly Distribution:
{rides_by_hour_df.nlargest(5, 'Rides').to_string()}

Daily Distribution:
{day_analysis.to_string()}

{'='*70}
VEHICLE PERFORMANCE
{'='*70}

{vehicle_fare.to_string()}

{'='*70}
SURGE PRICING ANALYSIS
{'='*70}

{surge_analysis.to_string()}

{'='*70}
RECOMMENDATIONS
{'='*70}

1. ⏰ PEAK HOUR OPTIMIZATION
   • Highest demand at {peak_hour}:00
   • Increase driver incentives during peak hours (7-9 AM, 5-7 PM)
   • Target driver recruitment for peak periods

2. 🚙 VEHICLE STRATEGY
   • Premium vehicles generate {(vehicle_fare['Premium']/vehicle_fare['Economy'] - 1)*100:.1f}% higher fares
   • Expand premium fleet for higher margins
   • Keep economy fleet for volume

3. 💰 SURGE PRICING
   • Surge multiplier effectiveness: {completed_rides['surge_multiplier'].mean():.2f}x average
   • Implement surge on {busiest_day}s for maximum revenue
   • Balance surge with customer satisfaction

4. 📊 QUALITY CONTROL
   • Current average rating: {completed_rides['ride_rating'].mean():.2f}/5
   • Target: Improve to 4.5+/5
   • Focus on short trips for rating improvement

5. 🎯 CANCELLATION REDUCTION
   • Current cancellation rate: {(df['is_cancelled'].sum()/len(df)*100):.2f}%
   • Target: Reduce to 2%
   • Lost revenue: ${df[df['is_cancelled']==1]['total_fare'].sum():.2f}

6. 📈 REVENUE GROWTH
   • Current average fare: ${avg_fare:.2f}
   • Target: ${avg_fare * 1.25:.2f} (25% increase)
   • Strategies: Premium services, surge pricing, long-distance incentives

{'='*70}
END OF REPORT
{'='*70}
"""

report_path = os.path.join(OUTPUT_DIR, 'analysis_report.txt')
with open(report_path, 'w') as f:
    f.write(report_text)

print(f"✅ Report saved: {report_path}")

# ============================================================
# SAVE ANALYSIS SUMMARY
# ============================================================
summary_data = {
    'Metric': [
        'Total Rides',
        'Completed Rides',
        'Cancellation Rate (%)',
        'Total Revenue ($)',
        'Average Fare ($)',
        'Average Distance (km)',
        'Average Duration (min)',
        'Average Rating (1-5)',
        'Peak Hour',
        'Busiest Day',
        'Top Vehicle Type',
        'Most Used Payment'
    ],
    'Value': [
        f"{len(df):,}",
        f"{len(completed_rides):,}",
        f"{(df['is_cancelled'].sum()/len(df)*100):.2f}",
        f"{total_revenue:,.2f}",
        f"{avg_fare:.2f}",
        f"{avg_distance:.2f}",
        f"{avg_duration:.2f}",
        f"{completed_rides['ride_rating'].mean():.2f}",
        f"{peak_hour}:00",
        busiest_day,
        vehicle_dist.index[0],
        payment_dist.index[0]
    ]
}

summary_df = pd.DataFrame(summary_data)
summary_path = os.path.join(OUTPUT_DIR, 'summary_statistics.csv')
summary_df.to_csv(summary_path, index=False)
print(f"✅ Summary statistics saved: {summary_path}")

# ============================================================
# FINAL SUMMARY
# ============================================================
print("\n\n" + "="*70)
print(" " * 20 + "✅ ANALYSIS COMPLETE!")
print("="*70)

print("\n📁 OUTPUT FILES GENERATED:")
print(f"  📊 Dashboard 1 (Main):       dashboard_1_main_analysis.png")
print(f"  📊 Dashboard 2 (Advanced):   dashboard_2_advanced_analysis.png")
print(f"  📋 Full Report:              analysis_report.txt")
print(f"  📈 Summary Statistics:       summary_statistics.csv")
print(f"  💾 Full Dataset:             ride_sharing_data.csv")

print(f"\n📂 All files saved in: {os.path.abspath(OUTPUT_DIR)}")

print("\n🎯 NEXT STEPS:")
print("  1. Review the generated dashboards and report")
print("  2. Export data for further analysis in Excel/PowerBI")
print("  3. Share findings with stakeholders")
print("  4. Implement recommendations")
print("  5. Monitor KPIs regularly")

print("\n✨ Thank you for using Ride-Sharing Analysis Tool!")
print("="*70 + "\n")